name             'dev'
maintainer       'maintainer'
maintainer_email 'email@gmail.com'
license          'All rights reserved'
description      'Installs/Configures dev'
long_description 'Installs/Configures dev'
version          '0.1.0'
